import * as express from 'express'
import { NextFunction, Request, Response } from 'express'

import { getMetrics } from '../services/metrics'

const metricsRouter = express.Router()

/**
 * Routes for the metrics report generated by prometheus
 */
metricsRouter.get(
  '/',
  (_req: Request, res: Response, next: NextFunction): void => {
    res.set('Content-Type', 'text/plain')
    res.send(getMetrics())
    return next()
  },
)

export default metricsRouter
